// Common fields shared by every catalog item.
type CatalogItemBase = {
  label: string;
  picture?: string;
};

export type FurnitureItem = CatalogItemBase & {
  kind: "furniture";
  assetId: string;
  url: string;
};

type WallItem = CatalogItemBase & {
  kind: "wall";
};

type LightItem = CatalogItemBase & {
  kind: "light";
  lightType: "point" | "spot" | "area";
};

export type CatalogItem = FurnitureItem | WallItem | LightItem;

type CatalogSection = {
  category: string;
  items: CatalogItem[];
};

// Furniture entries are generated by scripts/catalog-pipeline.mjs:
// it opens every GLB/glTF under public/models, screenshots it, and
// rewrites catalog.models.ts. Walls and lights stay hand-maintained
// here because they have no asset file to screenshot.
import { CATALOG_FURNITURE } from "./catalog.models";

const CATEGORY_ORDER = ["Sofas", "Chairs", "Tables", "Cabinets"];

const furnitureSections: CatalogSection[] = Object.keys(CATALOG_FURNITURE)
  .sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a);
    const bi = CATEGORY_ORDER.indexOf(b);
    return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
  })
  .map((category) => ({ category, items: CATALOG_FURNITURE[category] }));

export const CATALOG: CatalogSection[] = [
  ...furnitureSections,
  {
    category: "Structure",
    items: [
      {
        kind: "wall",
        label: "Wall",
      },
    ],
  },
  {
    category: "Lighting",
    items: [
      {
        kind: "light",
        label: "Point Light",
        lightType: "point",
      },
    ],
  },
];

// assetId -> GLB url, derived from the catalog. Only furniture has a url,
// so the type-predicate filter keeps walls (and anything urless) out.
export const registory: Record<string, string> = Object.fromEntries(
  CATALOG.flatMap((section) => section.items)
    .filter((item): item is FurnitureItem => item.kind === "furniture")
    .map((item) => [item.assetId, item.url]),
);
