import type { FurnitureItem } from "./catalog";

// AUTO-GENERATED by scripts/catalog-pipeline.mjs
// Do not edit by hand. To (re)generate: `npm run catalog`
export const CATALOG_FURNITURE: Record<string, FurnitureItem[]> = {
  "Sofas": [
    {
      kind: "furniture",
      label: "Sofa",
      assetId: "sofa",
      url: "/models/sofas/sofa.glb",
      picture: "/models/sofas/sofa_thumb.png",
    },
    {
      kind: "furniture",
      label: "Sofa 02 2k",
      assetId: "sofa_02_2k",
      url: "/models/sofas/sofa_02_2k.gltf/sofa_02_2k.gltf",
      picture: "/models/sofas/sofa_02_2k.gltf/sofa_02_2k_thumb.png",
    }
  ],
  "Tables": [
    {
      kind: "furniture",
      label: "Gallinera Table 2k",
      assetId: "gallinera_table_2k",
      url: "/models/tables/gallinera_table_2k.gltf/gallinera_table_2k.gltf",
      picture: "/models/tables/gallinera_table_2k.gltf/gallinera_table_2k_thumb.png",
    },
    {
      kind: "furniture",
      label: "Gothic Coffee Table 2k",
      assetId: "gothic_coffee_table_2k",
      url: "/models/tables/gothic_coffee_table_2k.gltf/gothic_coffee_table_2k.gltf",
      picture: "/models/tables/gothic_coffee_table_2k.gltf/gothic_coffee_table_2k_thumb.png",
    },
    {
      kind: "furniture",
      label: "Round Wooden Table 02 2k",
      assetId: "round_wooden_table_02_2k",
      url: "/models/tables/round_wooden_table_02_2k.gltf/round_wooden_table_02_2k.gltf",
      picture: "/models/tables/round_wooden_table_02_2k.gltf/round_wooden_table_02_2k_thumb.png",
    }
  ],
  "Cabinets": [
    {
      kind: "furniture",
      label: "ClassicNightstand 01 2k",
      assetId: "ClassicNightstand_01_2k",
      url: "/models/cabinets/ClassicNightstand_01_2k.gltf/ClassicNightstand_01_2k.gltf",
      picture: "/models/cabinets/ClassicNightstand_01_2k.gltf/ClassicNightstand_01_2k_thumb.png",
    },
    {
      kind: "furniture",
      label: "Vintage Cabinet 01 2k",
      assetId: "vintage_cabinet_01_2k",
      url: "/models/cabinets/vintage_cabinet_01_2k.gltf/vintage_cabinet_01_2k.gltf",
      picture: "/models/cabinets/vintage_cabinet_01_2k.gltf/vintage_cabinet_01_2k_thumb.png",
    }
  ]
};
